name: Deploy Hugo Site

permissions:
  id-token: write
  contents: read
  pages: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Remote all web content 
      run: |
        rm -f *
        rm -rf ./public
        rm -rf ./hugo-site

    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        submodules: 'recursive'
        token: ${{ secrets.PUBLIC_REPO_ACCESS_PAT_TOKEN }}

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Setup checkout and print diagnostics
      run: |
        mv -f ./hugo-site/* ./
        pwd
        ls -al

    - name: GC
      run: hugo --gc --config ./hugo.yaml

    - name: Build
      run: hugo --config ./hugo.yaml --buildDrafts --ignoreCache --enableGitInfo --minify

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: './public'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
